### ISSUE TITLE
Link project to Branch

### ISSUE THREAD

**Issue by mindspank** [kmpm/node-qvx#2]
Hey,

We would love it if you wanted to link the repo into the open source community around Qlik, Branch.
[Qlik Branch](http://branch.qlik.com/)  

No need to manage any additional resource and we won't spam you :)

**Comment by kmpm** [comment]
I would if I could....

I actually tried
- signed up for an account (not using github)
- Clicked Create Project
- Logged in to github to select project...
- !!! FAIL Can not select node-qvx because the list of projects shown is not long enough so it doesn't contain node-qvx.

**Comment by kmpm** [comment]
Removed 10 repositories or so and then it worked.

One thing though... This project is not bound to either QlikView or Sense but I had to select a product to categorize it and selected QlikView since I had used that the most

**Comment by mindspank** [comment]
Ha, thanks for letting us know. We'll make sure the list overflows correctly today :)

Ye, QVX is that in the middle category which we could not fit in anywhere
